# mobile/scripts/test_quantized_desktop.py
"""
Quick sanity‑check for the INT8‑quantized ViT model.

- Loads the TFLite model generated by ai‑edge‑torch.
- Loads the original FP32 ONNX model (used by the desktop Streamlit app).
- Runs inference on the same sample image.
- Prints the top‑3 class indices and logits for both models.
- Shows the latency (average over 10 runs) for each backend.
"""

import time
from pathlib import Path

import numpy as np
from PIL import Image

# -------------------------------------------------
# Helpers – preprocessing (same for both back‑ends)
# -------------------------------------------------
def preprocess(img_path: Path) -> np.ndarray:
    """Resize → normalize → NHWC float32 array (TensorFlow‑Lite expects NHWC)."""
    img = Image.open(img_path).convert("RGB")
    img = img.resize((224, 224))
    arr = np.asarray(img).astype(np.float32) / 255.0
    # ImageNet mean / std
    mean = np.array([0.485, 0.456, 0.406], dtype=np.float32)
    std  = np.array([0.229, 0.224, 0.225], dtype=np.float32)
    arr = (arr - mean) / std
    # Add batch dimension → (1, 224, 224, 3)
    return arr[np.newaxis, ...]

# -------------------------------------------------
# Load TFLite model
# -------------------------------------------------
def run_tflite(model_path: Path, input_data: np.ndarray) -> tuple[np.ndarray, float]:
    # TensorFlow Lite interpreter – works after installing full TensorFlow
    import tensorflow as tf
    Interpreter = tf.lite.Interpreter

    interpreter = Interpreter(model_path=str(model_path))
    interpreter.allocate_tensors()

    input_idx  = interpreter.get_input_details()[0]["index"]
    output_idx = interpreter.get_output_details()[0]["index"]

    # Warm‑up
    interpreter.set_tensor(input_idx, input_data)
    interpreter.invoke()

    runs = 10
    times = []
    for _ in range(runs):
        start = time.time()
        interpreter.set_tensor(input_idx, input_data)
        interpreter.invoke()
        times.append(time.time() - start)

    logits = interpreter.get_tensor(output_idx)
    avg_ms = sum(times) / runs * 1000
    return logits, avg_ms

# -------------------------------------------------
# Load ONNX model (the FP32 baseline)
# -------------------------------------------------
def run_onnx(model_path: Path, input_data: np.ndarray) -> tuple[np.ndarray, float]:
    import onnxruntime as ort

    # ONNX Runtime expects NCHW, so transpose
    nchw = np.transpose(input_data, (0, 3, 1, 2))

    sess = ort.InferenceSession(str(model_path), providers=["CPUExecutionProvider"])
    input_name = sess.get_inputs()[0].name
    output_name = sess.get_outputs()[0].name

    # Warm‑up
    sess.run([output_name], {input_name: nchw})

    runs = 10
    times = []
    for _ in range(runs):
        start = time.time()
        sess.run([output_name], {input_name: nchw})
        times.append(time.time() - start)

    logits = sess.run([output_name], {input_name: nchw})[0]
    avg_ms = sum(times) / runs * 1000
    return logits, avg_ms

# -------------------------------------------------
# Main entry point
# -------------------------------------------------
if __name__ == "__main__":
    repo_root = Path(__file__).parents[2]
    tflite_path = repo_root / "mobile" / "assets" / "vit_model_ai_edge.tflite"
    onnx_path   = repo_root / "mobile" / "assets" / "vit_model.onnx"
    sample_img  = repo_root / "data" / "sample.jpg"

    if not sample_img.exists():
        raise FileNotFoundError(
            f"Sample image not found at {sample_img}. Place any JPEG there – it will be resized automatically."
        )

    input_np = preprocess(sample_img)

    # TFLite inference
    tflite_logits, tflite_latency = run_tflite(tflite_path, input_np)
    print("\n=== TFLite (INT8) ===")
    print(f"Avg inference time: {tflite_latency:.1f} ms")
    print(f"Logits shape: {tflite_logits.shape}")
    top3_tflite = np.argsort(tflite_logits[0])[-3:][::-1]
    print(f"Top‑3 class indices (INT8): {top3_tflite}")

    # ONNX inference
    onnx_logits, onnx_latency = run_onnx(onnx_path, input_np)
    print("\n=== ONNX (FP32) ===")
    print(f"Avg inference time: {onnx_latency:.1f} ms")
    print(f"Logits shape: {onnx_logits.shape}")
    top3_onnx = np.argsort(onnx_logits[0])[-3:][::-1]
    print(f"Top‑3 class indices (FP32): {top3_onnx}")

    # Similarity check
    from numpy.linalg import norm
    cos_sim = np.dot(tflite_logits[0], onnx_logits[0]) / (norm(tflite_logits[0]) * norm(onnx_logits[0]))
    print(f"\nCosine similarity between INT8 and FP32 logits: {cos_sim:.4f}")
    print("\n✅ Test completed. If the top‑3 indices match (or are very close) and similarity is high, the quantized model is ready for deployment.")
